#######################################################################################
# Book settings
title: ""
logo: images/logo.png
author: leroy
copyright: '2025'
email: vanpipy@gmail.com
description: Note here, there and anywhere

# exclude something
# exclude_patterns: [file-types/include-rst.rst]

# Bibliography settings
bibtex_bibfiles:
  - references.bib

execute:
  execute_notebooks: cache
  stderr_output: "remove"
  allow_errors: true
  timeout: 120

html:
  # FIXME: surely we could allow internal or relative links somehow?
  # (The documentation says only that HTML is allowed, nothing about the base URL is mentioned.)
  # Then we could link to the changelog in the *same* build of the docs.
  # announcement: Note here, there and anywhere
  favicon: images/favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: false
  baseurl: https://vanpiyp.github.io

repository:
  url: https://github.com/vanpipy/vanpipy.github.io.git
  branch: gh-pages
  path_to_book: notebook

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  thebe: true

parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

sphinx:
  recursive_update: true
  config:
    bibtex_reference_style: author_year # or label, super, \supercite
    # unknown_mime_type - application/vnd.plotly.v1+json and application/vnd.bokehjs_load.v0+json
    # domains - sphinx_proof.domain::prf needs to have `resolve_any_xref` method
    # mime_priority - latex priority not set in myst_nb for text/html, application/javascript
    suppress_warnings:
      ["mystnb.unknown_mime_type", "myst.domains", "mystnb.mime_priority"]
    copybutton_prompt_text: "$"
    nb_execution_show_tb: True
    nb_execution_timeout: 120
    html_extra_path:
      - images/badge.svg
    intersphinx_mapping:
      ebp:
        - "https://executablebooks.org/en/latest/"
        - null
      myst-parser:
        - "https://myst-parser.readthedocs.io/en/latest/"
        - null
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
      sphinx:
        - "https://www.sphinx-doc.org/en/master"
        - null
      nbformat:
        - "https://nbformat.readthedocs.io/en/latest"
        - null
      sd:
        - https://sphinx-design.readthedocs.io/en/latest
        - null
    language: en
    latex_elements:
      sphinxsetup: "iconpackage=fontawesome"
      preamble: |
        \newcommand\N{\mathbb{N}}
        \newcommand\floor[1]{\lfloor#1\rfloor}
        \newcommand{\bmat}{\left[\begin{array}}
        \newcommand{\emat}{\end{array}\right]}

    html_theme_options:
      navigation_with_keys: false

  extra_extensions:
    - sphinx_click.ext
    - sphinx_inline_tabs
    - sphinx_proof
    - sphinx_examples
    # - sphinxext.rediraffe