title: Leap Day For Youself
description: Leap Leap Leap.

theme: jekyll-theme-leap-day

exclude:
    - .git/
    - lib/
    - Gemfile
    - README.md

github:
    is_project_page: true
    owner_url: https://github.com/vanpipy
    owner_name: vanpipy
